### ISSUE TITLE
The password is wrong

### ISSUE THREAD

**Issue by 24mlight** [petrosb-codes/nlp-fraud-detection#2]
I had tried FraudNLP and fraudnlp, but both wrong.

**Comment by pboulieris** [comment]
Are you sure? I just downloaded the file and unzipped it successfully with "FraudNLP".

**Comment by 24mlight** [comment]
YES，I've tried several types zip software.
![image](https://github.com/pboulieris/FraudNLP/assets/45850482/5c8e1ef0-364a-44bb-89e9-c6f19c1120d4)
![image](https://github.com/pboulieris/FraudNLP/assets/45850482/7f3ddd2d-f538-4ef8-a4d5-05f12c6bc06c)

**Comment by pboulieris** [comment]
Try with winrar.

**Comment by 24mlight** [comment]
I redownload the entire GitHub repository，and it works, THANKS.
