### ISSUE TITLE
I met virus when I want to download the whole code

### ISSUE THREAD

**Issue by andrew76214** [petrosb-codes/nlp-fraud-detection#5]
As title, I met virus when I want to download the whole code.
What's going on?

**Comment by pboulieris** [comment]
It's a single .pkl file.
It's obviously got something to do with your machine, but I ran it through virustotal out of curiosity.

Here's the report.
https://www.virustotal.com/gui/file/b160f433d4384c7cdd821fb63d03b17ceeb9bd1a58a371aae44a1a7bffafced5
